### PR TITLE
fix(jwt): update nonce value in challenge JWT cookie to be a string

### LINKED ISSUE #468: Change non-string JWT claims to be strings
Apparently downstream consumers are using the contents of the JWT to do external validation logic. This realization horrifies me.

### PR DESCRIPTION
**Pull request by JasonLovesDoggo**
Closes #468

Checklist:

- [x] Added a description of the changes to the `[Unreleased]` section of docs/docs/CHANGELOG.md
- [ ] Added test cases to [the relevant parts of the codebase](https://anubis.techaro.lol/docs/developer/code-quality)
- [ ] Ran integration tests `npm run test:integration` (unsupported on Windows, please use WSL)
(did not run integration tests, will see if CI passes :) )

### CODE REVIEW

File: lib/anubis.go [hunk 1]
```diff
@@ -344,7 +345,7 @@ func (s *Server) PassChallenge(w http.ResponseWriter, r *http.Request) {
 	// generate JWT cookie
 	token := jwt.NewWithClaims(jwt.SigningMethodEdDSA, jwt.MapClaims{
 		"challenge": challenge,
-		"nonce":     nonce,
+		"nonce":     nonceStr,
```
Comment (Xe) [inline lib/anubis.go:348]: I love how elegant this is.

**Review by Xe — APPROVED** [review]
LGTM!

File: lib/anubis.go (hunk 1 above)
Comment (JasonLovesDoggo) [reply lib/anubis.go:348]: yeahh 😂 I originally started typing `strconv.Atoi(non` and then my auto suggest was like "nonceStr!!!"
