### PR TITLE
fix(config): remove trailing newlines in regexes

### LINKED ISSUE #372: Default botPolicy rule for Opera|Mozilla doesn't detect Opera
In my installation running [v1.17.0-beta1](https://github.com/TecharoHQ/anubis/releases/tag/v1.17.0-beta1), it looks like the default botPolicy for generic browsers with

```
"user_agent_regex": "Mozilla|Opera\n",
```

isn't detecting Opera properly, I see a ton of unwanted connections on the protected backend. Connections with the "Mozilla" user agent are filtered as expected.

However, changing the policy to
```
"user_agent_regex": "Mozilla|Opera",
```

fixes the issues, and both the Mozilla and Opera strings are properly detected now.

Can someone confirm?

The malicious requests I see have the user agent string set to
```
a) "Opera/9.56.(Windows 98; om-KE) Presto/2.9.186 Version/12.00"
b) "Opera/8.88.(Windows NT 6.1; sat-IN) Presto/2.9.175 Version/10.00"
```

and more variants of this pattern.

### PR DESCRIPTION
**Pull request by Xe**
Closes #372

Fun YAML fact of the day:

What is the difference between how these two expressions are parsed?

```yaml
foo: >
  bar
```

```yaml
foo: >-
  bar
```

They are invisible in yaml, but when you evaluate them to JSON the difference is obvious:

```json
{
  "foo": "bar\n"
}
```

```json
{
  "foo": "bar"
}
```

User-Agent strings, URL path values, and HTTP headers _do_ end in newlines in HTTP/1.1 wire form, but that newline is usually stripped before the server actually handles it. Also HTTP/2 is a thing and does not terminate header values with newlines.

This change makes Anubis more aggressively detect mistaken uses of the yaml `>` operator and nudges the user into using the yaml `>-` operator which does not append the trailing newline.

I had honestly forgotten about this YAML behavior because it wasn't relevant for so long. Oops! Glad I released a beta.

Whenever you get into this state, Anubis will throw a config parsing error and then give you a message hinting at the folly of your ways.

```
config.Bot: regular expression ends with newline (try >- instead of > in yaml)
```

Big thanks to https://yaml-multiline.info, this helped me realize my folly instantly.

@aiverson, this is official permission to say "told you so".

Checklist:

- [x] Added a description of the changes to the `[Unreleased]` section of docs/docs/CHANGELOG.md
- [x] Added test cases to [the relevant parts of the codebase](https://anubis.techaro.lol/docs/developer/code-quality)
- [x] Ran integration tests `npm run test:integration` (unsupported on Windows, please use WSL)

### CODE REVIEW

File: lib/policy/checker.go [hunk 1]
```diff
@@ -110,11 +110,11 @@ func NewUserAgentChecker(rexStr string) (Checker, error) {
 }
 
 func NewHeaderMatchesChecker(header, rexStr string) (Checker, error) {
-	rex, err := regexp.Compile(rexStr)
+	rex, err := regexp.Compile(strings.TrimSpace(rexStr))
```
Comment (Xe) [inline lib/policy/checker.go:113]: Even though it's not possible for Anubis' normal config loading route to end with trailing spaces here, be paranoid.

**Comment by boydaihungst** [comment]
Can't install on Ubuntu amd64. Got this error:
```
Get:1 /home/huyhoang/anubis_1.17.0-beta2_amd64.deb anubis amd64 .17.0-beta2 [4,642 kB]
dpkg: error processing archive /home/huyhoang/anubis_1.17.0-beta2_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'anubis':
 'Version' field value '.17.0-beta2': version number does not start with digit
Errors were encountered while processing:
 /home/huyhoang/anubis_1.17.0-beta2_amd64.deb
N: Download is performed unsandboxed as root as file '/home/huyhoang/anubis_1.17.0-beta2_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Xe** [comment]
https://github.com/TecharoHQ/anubis/releases/tag/v1.17.0-beta3 <- fixed packages will show up here

TODO: make sure that packages are installable in a CI test

**Comment by Xe** [comment]
or not, ugh, did i somehow break git tag resolution logic by having two tags point to the same commit?

**Comment by boydaihungst** [comment]
Yep, I just noticed it.

**Comment by Xe** [comment]
https://github.com/TecharoHQ/anubis/releases/tag/v1.17.0-beta4 this is actually fixed including a summary of the problem. I will develop automation for this in the near future.
